version: "3.8"
services:
  shambot:
    image: shambot
    build: .
    environment:
      - SHAMBOT_TOKEN=${SHAMBOT_TOKEN}
      - SHAMBOT_CLIENTID=${SHAMBOT_CLIENTID}
      - SHAMBOT_PG_USER=${SHAMBOT_PG_USER}
      - SHAMBOT_PG_PASS=${SHAMBOT_PG_PASS}
    depends_on:
      - "db"
  db:
    image: postgres:13.8-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${SHAMBOT_PG_PASS}
      - POSTGRES_USER=${SHAMBOT_PG_USER}
      - POSTGRES_DB=shambot-db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"